### ISSUE TITLE
category - related categories. Vymysliet algoritmus hladania produktov

### ISSUE THREAD

**Issue by xkovacikm** [orchidsphere/sensashop#14]

**Comment by orchidsphere** [comment]
Skúsil by som recyklovať ten z mackov, je dobrý a používa redis. Akurát nie sú žiadne dáta z objednávok, podľa ktorých by sa hľadalo

**Comment by orchidsphere** [comment]
Ak nie sú dáta, vybral som 16 produktov, ktoré majú label.
Vyriešené
