### ISSUE TITLE
.input-group-btn Nesedia výšky tlačidla a inputu

### ISSUE THREAD

**Issue by orchidsphere** [orchidsphere/sensashop#20]
<img width="574" alt="screen shot 2016-10-26 at 16 52 10" src="https://cloud.githubusercontent.com/assets/13481698/19731156/d186cf6c-9b9c-11e6-9271-6a14b7617069.png">

**Comment by xkovacikm** [comment]
.custom.less -> .input-group{} vyriesene. Nechavam otvorene ak by sa nahodou niekde objavil bug, kde to nesedi.
