### ISSUE TITLE
Detail product - description collapse "read less" pridat

### ISSUE THREAD

**Issue by xkovacikm** [orchidsphere/sensashop#5]

**Comment by xkovacikm** [comment]
a zistit ako je to s tymi 4 malymi obrazkami na detaile produktu. Aby sme to nejako vedeli zarovnat

**Comment by xkovacikm** [comment]
read less pridane

**Comment by orchidsphere** [comment]
Čítať viac je nalepené na nav-tab

<img width="1204" alt="screen shot 2016-10-26 at 18 08 27" src="https://cloud.githubusercontent.com/assets/13481698/19734269/3708171a-9ba7-11e6-97d8-bfb4f9bb428c.png">

Po rozkliknutí *Read more* ide schovaný text na nový riadok, kvôli
.collapse.in {
    display: block;
}
