### ISSUE TITLE
Detail product - nie je v DB stockstate. Neda sa nastylovat ciselnik pre mnozstvo objednania

### ISSUE THREAD

**Issue by xkovacikm** [orchidsphere/sensashop#7]

**Comment by xkovacikm** [comment]
+ tam bude treba riesit aj velkost vedlajsieho textu v responzivite

**Comment by orchidsphere** [comment]
Zvláštne správenie, v sk.config.php je vypnuté sledovanie skladového stavu, tj. všetko by sa malo dať kúpiť.

**Comment by orchidsphere** [comment]
Nová metóda ProductModel::eligibleToBuy() to rieši a zároveň rieši aj chaos vo views.
@see method reference

**Comment by orchidsphere** [comment]
Ale nehrnul by som sa do štýlovanie podľa návhru, myslím, že default vyzerá lepšie. Nie je taký obrý.
